we got this issue in the preview :
Error: ./src/lib/firebase.ts:31:7
Ecmascript file had an error
  29 |
  30 | // Initialize Firebase
> 31 | const app = initializeApp(firebaseConfig);
     |       ^^^
  32 |
  33 | // Initialize Firestore and Auth
  34 | const db = getFirestore(app);

the name `app` is defined multiple times

    at <unknown> (Error: ./src/lib/firebase.ts:31:7)
    at Object.getCompilationErrors (file:///home/user/studio/node_modules/next/dist/server/dev/hot-reloader-turbopack.js:722:59)
    at DevBundlerService.getCompilationError (file:///home/user/studio/node_modules/next/dist/server/lib/dev-bundler-service.js:39:55)
    at DevServer.getCompilationError (file:///home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:643:42)
    at DevServer.findPageComponents (file:///home/user/studio/node_modules/next/dist/server/dev/next-dev-server.js:613:43)
    at async DevServer.renderErrorToResponseImpl (file:///home/user/studio/node_modules/next/dist/server/base-server.js:2604:26)